FROM ruby:3.0.0-alpine3.13

ARG DB_NAME
ARG DB_USER
ARG DB_PASS

ENV ROOT="/rails"

ENV RAILS_ENV="development"
ENV RAILS_DB_NAME=${DB_NAME}
ENV RAILS_DB_USER=${DB_USER}
ENV RAILS_DB_PASS=${DB_PASS}

RUN apk update
RUN apk add --no-cache make
RUN apk add --no-cache alpine-sdk
RUN apk add --no-cache build-base
RUN apk add --no-cache sqlite-libs
RUN apk add --no-cache postgresql-dev
RUN apk add --no-cache --virtual=.build-deps \
    git \
    openssh-client \
    #mariadb-dev \
    #sqlite-dev \
    vips-dev \
    pkgconfig \
    nodejs \
    zlib-dev \
    libxml2-dev \
    libxslt-dev \
    readline-dev \
    tzdata \
    && apk del .build-deps

WORKDIR ${ROOT}

COPY Gemfile ${ROOT}
COPY Gemfile.lock ${ROOT}

RUN gem install bundler

RUN bundle update
RUN bundle install
