version: '3.7'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
    ports:
      - 3000:3000
    restart: unless-stopped
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
      - blang-network
  pgsql:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      blang-network:
        ipv4_address: 172.19.0.10
    
networks:
  blang-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
